stages:
  - build
  - test
  - staging
  - production

variables:
  APP_VERSION: $CI_PIPELINE_IID

Build Website:
  stage: build
  image: node:22-alpine
  script:
    - npm install 
    - npm run lint
    - npm run build
    - echo $APP_VERSION > build/version.html
  artifacts:
    paths:
      - build

Test Webisite:
  stage: test
  image: node:22-alpine
  script:
    - npm install --global serve
    - apk add curl
    - serve -s build & 
    - sleep 15
    - curl http://localhost:3000 | grep "React App"

.deploy:
  image: 
    name: amazon/aws-cli:2.22.17
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete
    - curl $CI_ENVIRONMENT_URL | grep "React App"
    - curl $CI_ENVIRONMENT_URL/version.html | grep $APP_VERSION

Deploy to Staging:
  stage: staging
  environment: staging
  extends: .deploy

Deploy to Production:
  stage: production
  environment: production
  when: manual
  extends: .deploy
